01_Django/articles/urls.py
from django.urls import path

# 명시적 상대경로
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    
    # 변수 값에 따라 하나의 path()에 여러 페이지를 연결시킬 수 있음
    # 변수는 <> 안에 정의, views 함수의 인자로 할당됨
    path('hello/<str:name>/', views.hello, name='hello'),
]

01_Django/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

01_Django/pages/urls.py
from django.urls import path
# 명시적 상대경로
from . import views

# 당장 path를 쓰지 않더라도 urlpatterns는 작성해야 함
app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

01_Django/articles/views.py
from multiprocessing import context
import random
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'articles/index.html')


def greeting(request):
    # context 데이터가 많아질 경우, 다음과 같이 작성하는 것이 바람직
    foods = ['apple', 'banana', 'coconut', 'mango', 'grape']
    info = {
        'name' : 'Alice',
    }

    # 다른 이름으로 사용 가능하지만, 관행적으로 context 사용 
    context = {
        'info' : info,
        'foods' : foods,
    }
    return render(request, 'articles/greeting.html', context)


def dinner(request):
    foods = ['apple', 'banana', 'coconut', 'mango', 'grape']
    pick = random.choice(foods)
    context = {
        'pick' : pick,
        'foods' : foods,
    }
    return render(request, 'articles/dinner.html', context)


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # throw에서 보낸 데이터를 찾아서 저장
    # print(request)
    # print(type(request))
    # print(request.GET)
    # print(request.GET.get('message'))
    message = request.GET.get('message')
    context = {
        'message' : message,
    }
    return render(request, 'articles/catch.html', context)

def hello(request, name):
    context = {
        'name' : name,
    }
    return render(request, 'articles/hello.html', context)

01_Django/pages/views.py
from pydoc import render_doc
import re
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

01_Django/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>Catch</h1>
  <h3>여기서 {{ message }}를 받았다!!</h3>
  <a href="{% url 'articles:throw' %}">다시 던지기 {# (Throw) #}</a>
{% endblock content %}

01_Django/articles/templates/articles/dinner.html
{% extends 'base.html' %}

{% block content %}
  {# filters 사용 #}
  <p>{{ pick }}는 {{ pick|length }}글자입니다.</p>
  <p>{{ foods|join:", " }}</p>

  <p>메뉴판</p>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  
  {# 한줄 주석 #}
  {% comment %} 
    <p>주석</p>
    <h2>여러 줄 주석</h2>
  {% endcomment %}
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

01_Django/articles/templates/articles/greeting.html
{% extends 'base.html' %}

{% block content %}
  <h1>안녕하세요, {{ info.name }} 입니다.</h1>
  <p>저는 {{ foods.4 }}를 가장 좋아합니다.</p>

  <a href="{% url 'articles:index' %}">뒤로가기 {# (Index페이지로 이동)#} </a>
{% endblock content %}

01_Django/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello</h1>
  <h2>{{ name }}! Nice to meet you!!</h2>
{% endblock content %}

01_Django/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome 😄</h1>
<a href="{% url 'articles:greeting' %}">greeting</a>
<a href="{% url 'articles:dinner' %}">dinner</a>
<a href="{% url 'articles:throw' %}">throw</a>
<p></p>
<a href="{% url 'pages:index' %}">Move to Second App's Index Page</a>
{% endblock content %}

01_Django/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>Throw</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw</label>
    <input type="text" name="message" id="message">
    <input type="submit" value="던지기">
  </form>
  <a href="{% url 'articles:index' %}">뒤로가기 {# (Index) #}</a>

{% endblock content %}

01_Django/pages/templates/pages/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>Second App's Index Page</h1>
{% endblock content %}

01_Django/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
</body>

</html>