Like_Follow/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

Like_Follow/workshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

Like_Follow/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&family=Peralta&family=Permanent+Marker&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/6ed2bc1129.js" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  <div class="container m-5">
    {% if user.is_authenticated %}
    <h3>Hello, {{ user.username }}</h3>
    <a href="{% url 'accounts:profile' user.username %}" style="font-size: 1.25em;">MY PROFILE</a>
    <div class="d-flex align-items justify-content-end">
      <form action="{% url 'accounts:logout' %}" method="POST" class="d-inline">
        {% csrf_token %}
        <input type="submit" value="LOGOUT" class="btn btn-link text-decoration-none">
      </form>
      <a href="{% url 'accounts:update' %}" class="m-2">UPDATE</a>
      <form action="{% url 'accounts:delete' %}" method="POST" class="d-inline">
        {% csrf_token %}
        <input type="submit" value="UNREGISTER" class="btn btn-link text-decoration-none">
      </form>
    </div>
    {% else %}
    <a href="{% url 'accounts:login' %}">LOGIN</a>
    <a href="{% url 'accounts:signup' %}">SIGNUP</a>
    {% endif %}
    
    <hr>
    {% block content %}
  
    
    
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>