insta/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='password'),
    path('profile_update/', views.profile_update, name='profile_update'),
]

insta/instapjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<user_name>/', views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
]

insta/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.processors import Thumbnail
from imagekit.models import ProcessedImageField

# Create your models here.
class User(AbstractUser):
    pass


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=40, blank=True)
    introduction = models.TextField(blank=True)
    image_file = ProcessedImageField(
        blank=True,
        upload_to='photos/',
        processors=[Thumbnail(300, 300)],
        format='JPEG',
        options={'quality': 90},
    )

insta/posts/models.py
from django.db import models
from imagekit.processors import Thumbnail
from imagekit.models import ProcessedImageField

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    image = ProcessedImageField(
        blank=True,
        upload_to='photos/',
        processors=[Thumbnail(300, 300)],
        format='JPEG',
        options={'quality': 80},
    )

    def __str__(self):
        return self.content

insta/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import Profile


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
        )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

insta/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

insta/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
)
from .forms import CustomUserChangeForm, CustomUserCreationForm, ProfileForm
from django.views.decorators.http import (
    require_safe,
    require_POST,
    require_http_methods,
)
from django.contrib.auth.decorators import login_required
from .models import User, Profile


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('accounts:login')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
@login_required()
def delete(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            request.user.delete()
            auth_logout(request)
            return redirect('posts:index')
        else:
            return render(request, 'accounts/delete.html')
    else:
        return redirect('accounts:login')


@require_http_methods(['GET', 'POST'])
@login_required()
def update(request):
    User = get_user_model()
    user = User.objects.get(username=request.user)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance=user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@require_http_methods(['GET', 'POST'])
@login_required()
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('posts:index')

    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/password.html', context)


@require_safe
def profile(request, user_name):
    User = get_user_model()
    person = User.objects.get(username=user_name)
    profile = Profile.objects.get(user_id=person.pk)
    context = {
        'person': person,
        'profile': profile,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def profile_update(request):
    User = get_user_model()
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile', request.user)
    else:
        form = ProfileForm(instance=profile)

    context = {
        'form': form,
    }
    return render(request, 'accounts/profile_update.html', context)

insta/posts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import (
    require_safe,
    require_POST,
    require_http_methods,
)
from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .models import Post

# Create your views here.
@require_safe
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


@require_http_methods(['GET', 'POST'])
@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/form.html', context)


@require_POST
def delete(request, post_pk):
    if request.user.is_authenticated:
        post = Post.objects.get(pk=post_pk)
        post.delete()
    return redirect('posts:index')


@require_http_methods(['GET', 'POST'])
@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'posts/form.html', context)

insta/accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원 탈퇴</h1>
  <p>탈퇴하면 회원 정보를 복구할 수 없습니다.</p>
  <p>정말로 탈퇴하시겠습니까?</p>
  <form action="{% url 'accounts:delete' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="탈퇴" class="btn btn-danger">
  </form>
{% endblock content %}

insta/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Log in</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary d-inline">
    <a href="{% url 'accounts:signup' %}" class="btn btn-success" >Sign up</a>
  </form>
{% endblock content %}

insta/accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호 변경</h1>
<br>
  <form action="{% url 'accounts:password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="변경" class="btn btn-primary">
  </form>
{% endblock content %}

insta/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  {% comment %} {% if person.user == user %} {% endcomment %}
    <h1>환영합니다! {{ person.username }}</h1>
  {% comment %} {% endif %} {% endcomment %}
  <br>
  {% if profile.nickname %}
    <p>닉네임 : {{ profile.nickname }}</p>
  {% endif %}
  {% if profile.introduction %}
    <p>자기소개 : {{ profile.introduction }}</p>
  {% endif %}
  {% if profile.image_file %}
    <img src="{{ profile.image_file.url }}" alt="{{ person.image_file }}">
  {% endif %}

  {% if user == request.user %}
  <form action="{% url 'accounts:logout' %}" method="POST" class="d-inline">
    {% csrf_token %}
    <input type="submit" value="로그아웃" class="btn btn-secondary">
  </form>
  <a href="{% url 'accounts:profile_update' %}" class="btn btn-warning">프로필 수정</a>
  <a href="{% url 'accounts:password' %}" class="btn btn-primary">비밀번호 변경</a>
  <a href="{% url 'accounts:delete' %}" class="btn btn-danger">회원 탈퇴</a>
{% endif %}
  
{% endblock content %}

insta/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block content %}
  <h1>프로필 수정</h1>
  <br>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <input type="submit" value="변경"  class="btn btn-warning">
  </form>



{% endblock content %}

insta/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign up</h1>
<br>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock content %}

insta/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>User Edit</h1>
<br>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정" class="btn btn-warning">
  </form>
{% endblock content %}